spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_db
    username: quiz
    password: quiz
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/${spring.profiles.active}
